singleQuote: true
semi: true
printWidth: 140
trailingComma: "es5"
tabWidth: 2
endOfLine: "lf"
bracketSpacing: true
importOrder: [ "^@core/(.*)$", "^@server/(.*)$", "^@ui/(.*)$", "^[./]" ],
importOrderSeparation: true,
importOrderSortSpecifiers: true
